### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by willchoprojects** [JBEI/ART#3]
Hello ART Team!

Thanks for publishing this great repository and the corresponding website – making this available is amazing!
I was wondering if you have a link to your Docker image, its name, or a Dockerfile that I could use to run your code.
I saw several mentions of Docker but I either missed or couldn't find something that would allow me to get set up in Docker.

Thank you again!

**Comment by chimaerase** [comment]
Hello,

Thanks for your interest in ART!  As noted in the second paragraph of the README:

> Please note that this repository does not contain ART source code. For information on how to access the library see the [License](https://github.com/JBEI/ART#license) section.

Once you go through the (often quite simple) licensing process and gain access to the ART code repo, there's an included Dockerfile and directions for building it.
